dataset:
  name: cifar10
  num_classes: 10
  pre_size: 32
  image_size: 32

  interpolation: bilinear
  normalization_type: cifar10

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data_info/train_cifar10.txt
    batch_size: 128
    shuffle: True
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data_info/test_cifar10.txt
    batch_size: 200
    shuffle: False
