exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
mark: default
seed: 0

num_gpus: 1
num_workers: 1
num_machines: 1
machine_rank: 0

preprocessor:
  name: base

network:
  pretrained: False

pipeline:
  name: train

trainer:
  name: fedadav

evaluator:
  name: base

optimizer:
  name: adam
  num_epochs: 200
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.00001

recorder:
  name: base
  save_all_models: False
